### ISSUE TITLE
Lacks a license

### ISSUE THREAD

**Issue by DL6AKU** [blunden/EMVConsole#2]
I would like to use the code in a research project, but this lacks a license. Please add one.

**Comment by blunden** [comment]
Ok. I'll add one tonight. We were discussing licensing it under either the MIT or 2-clause BSD license. I assume either of those will work for your project?

**Comment by DL6AKU** [comment]
Sure! Thanks for the quick response!

**Comment by blunden** [comment]
Done!

Even if you don't have to submit any changes back, I'd still be interested to know if you end up using it for anything interesting.

**Comment by DL6AKU** [comment]
> Even if you don't have to submit any changes back, I'd still be interested to know if you end up using it for anything interesting.

If the project is through and if I can (without breaking the NDA), I will.
Thank you very much!

**Comment by DL6AKU** [comment]
I can tell you that much: It has found its way into a fuzzer for a major vendor chip card. Hopefully we can release the code and results after the project, but I am not sure yet. I am just the code monkey :)
